FROM bellsoft/liberica-openjdk-centos:11.0.4

ADD ./build/libs/*.jar /root/app.jar
ADD ./docker-entrypoint.sh /root/docker-entrypoint.sh

ENV JAVA_OPTS_DEV="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

ENTRYPOINT ["/root/docker-entrypoint.sh"]

EXPOSE 8080
EXPOSE 8686
EXPOSE 5005
