---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: backend1
        image: localhost:5000/backend1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: CENTRALDOGMA_SERVER_HOST
          value: centraldogma.default.svc.cluster.local
        - name: CENTRALDOGMA_SERVER_PORT
          value: "36462"
        ports:
        - containerPort: 8081
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: backend1
spec:
  type: NodePort
  selector:
    app: backend1
  ports:
  - name: app
    protocol: TCP
    targetPort: 8081
    port: 8081
    nodePort: 31100
