---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: backend1
        image: localhost:5000/backend1
        env:
        - name: JAVA_OPTS
          value: >-
            -Djava.rmi.server.hostname=127.0.0.1
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.rmi.port=8686
            -Dcom.sun.management.jmxremote.port=8686
            -Dcom.sun.management.jmxremote.local.only=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.authenticate=false
            -XX:StartFlightRecording=name=on_startup,filename=/root/flight_recording.jfr,dumponexit=true,delay=2m,maxsize=512m
            -Xms128m -Xmx128m
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
        - containerPort: 8081
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: backend1
spec:
  type: NodePort
  selector:
    app: backend1
  ports:
  - name: app
    protocol: TCP
    targetPort: 8081
    port: 8081
    nodePort: 31100
