FROM openjdk:11-ea-28-slim

WORKDIR /root
ADD ./armeria-sandbox-backend1/build/libs/armeria-sandbox-backend1-*.jar ./armeria-sandbox-backend1.jar
ENTRYPOINT java -Xms128m -Xmx128m -jar ./armeria-sandbox-backend1.jar --spring.profiles.active=docker
EXPOSE 8081
