FROM matsumana/debian9-openjdk11 as builder

WORKDIR /root
ADD ./armeria-sandbox-backend1/build/libs/armeria-sandbox-backend1-*.jar ./app.jar
RUN jlink \
    --compress=2 \
    --module-path=/tmp/jdk-11/jmods \
    --add-modules=java.base,java.logging,java.sql,java.desktop,jdk.management,jdk.management.agent,jdk.naming.dns,jdk.unsupported \
    --output=jre



FROM debian:9.5-slim

WORKDIR /root
COPY --from=builder /root/app.jar ./app.jar
COPY --from=builder /root/jre ./jre

ENTRYPOINT /root/jre/bin/java \
    -Djava.rmi.server.hostname=127.0.0.1 \
    -Dcom.sun.management.jmxremote.rmi.port=8686 \
    -Dcom.sun.management.jmxremote.port=8686 \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    \
    -Xms128m -Xmx128m \
    \
    -jar /root/app.jar \
    \
    --spring.profiles.active=docker

EXPOSE 8081
EXPOSE 8686
