FROM openjdk:11-ea-28-slim

WORKDIR /root

ADD ./armeria-sandbox-backend2/build/libs/armeria-sandbox-backend2-*.jar ./armeria-sandbox-backend2.jar

ENTRYPOINT java \
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 \
\
-Djava.rmi.server.hostname=127.0.0.1 \
-Dcom.sun.management.jmxremote.rmi.port=8686 \
-Dcom.sun.management.jmxremote.port=8686 \
-Dcom.sun.management.jmxremote.ssl=false \
-Dcom.sun.management.jmxremote.authenticate=false \
\
-Xms128m -Xmx128m \
\
-jar ./armeria-sandbox-backend2.jar \
\
--spring.profiles.active=docker

EXPOSE 8082
EXPOSE 5005
EXPOSE 8686
