FROM openjdk:11-ea-28-slim

WORKDIR /root
ADD ./armeria-sandbox-frontend/build/libs/armeria-sandbox-frontend-*.jar ./armeria-sandbox-frontend.jar
ENTRYPOINT java -jar ./armeria-sandbox-frontend.jar --spring.profiles.active=docker
EXPOSE 8080
