FROM centos:7.5.1804 as builder

WORKDIR /tmp
RUN curl -L -O https://download.java.net/java/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz && \
    tar xvf openjdk-11_linux-x64_bin.tar.gz
ENV PATH=/tmp/jdk-11/bin:${PATH}

WORKDIR /root
ADD ./armeria-sandbox-frontend/build/libs/armeria-sandbox-frontend-*.jar ./app.jar
RUN jlink \
    --compress=2 \
    --module-path=/tmp/jdk-11/jmods \
    --add-modules=java.base,java.logging,java.sql,java.desktop,jdk.management,jdk.management.agent,jdk.naming.dns,jdk.unsupported \
    --output=jre



FROM centos:7.5.1804

WORKDIR /root
COPY --from=builder /root/app.jar ./app.jar
COPY --from=builder /root/jre ./jre

ENTRYPOINT /root/jre/bin/java \
    -Djava.rmi.server.hostname=127.0.0.1 \
    -Dcom.sun.management.jmxremote.rmi.port=8686 \
    -Dcom.sun.management.jmxremote.port=8686 \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    \
    -Xms128m -Xmx128m \
    \
    -jar ./app.jar \
    \
    --spring.profiles.active=docker

EXPOSE 8080
EXPOSE 8686
