FROM azul/zulu-openjdk-alpine:11.0.3

# Tini
# https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
# https://github.com/krallin/tini
RUN apk add --no-cache tini

ADD ./build/libs/*.jar /root/app.jar
ADD ./docker-entrypoint.sh /root/docker-entrypoint.sh

ENV JAVA_OPTS_DEV="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

ENTRYPOINT ["/sbin/tini", "--", "/root/docker-entrypoint.sh"]

EXPOSE 8080
EXPOSE 8686
EXPOSE 5005
