---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: armeria-sandbox-backend3
  labels:
    app: armeria-sandbox-backend3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: armeria-sandbox-backend3
  template:
    metadata:
      labels:
        app: armeria-sandbox-backend3
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: armeria-sandbox-backend3
        image: localhost:5000/armeria-sandbox-backend3
        env:
        - name: JAVA_OPTS
          value: >-
            -Djava.rmi.server.hostname=127.0.0.1
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.rmi.port=8686
            -Dcom.sun.management.jmxremote.port=8686
            -Dcom.sun.management.jmxremote.local.only=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.authenticate=false
            -Djava.net.preferIPv4Stack=true
            -Xlog:gc*=debug:/root/gc_%t_%p.log:time,level,tags:filesize=1024m,filecount=5
            -XX:StartFlightRecording=name=on_startup,filename=/root/flight_recording.jfr,dumponexit=true,delay=2m,maxsize=512m
            -Xms128m -Xmx128m
        args:
        - --spring.profiles.active=kubernetes
        - --logging.level.info.matsumana.armeria=DEBUG
        - --zipkin.endpoint=http://zipkin.default.svc.cluster.local:9411/api/v2/spans
        - --centraldogma.server.host=centraldogma.default.svc.cluster.local
        - --centraldogma.server.port=36462
        ports:
        - containerPort: 8080  # Application
        - containerPort: 8686  # JMX
        - containerPort: 5005  # Java debugger
#        resources:
#          requests:
#            memory: "128Mi"
#            cpu: "250m"
#          limits:
#            memory: "256Mi"
#            cpu: "250m"

---
kind: Service
apiVersion: v1
metadata:
  name: armeria-sandbox-backend3
spec:
  type: NodePort
  selector:
    app: armeria-sandbox-backend3
  ports:
  - name: app
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 31300
