FROM matsumana/debian9-openjdk11 as builder

RUN jlink \
    --compress=2 \
    --add-modules=java.base,java.logging,java.sql,java.desktop,jdk.management,jdk.management.agent,jdk.naming.dns,jdk.unsupported \
    --bind-services \
    --output=/tmp/jre



FROM debian:9.5-slim

COPY --from=builder /tmp/jre /root/jre
ADD ./build/libs/*.jar /root/app.jar

ENTRYPOINT /root/jre/bin/java \
    $JAVA_OPTS \
    \
    -jar /root/app.jar

EXPOSE 8080
EXPOSE 8686
