---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: frontend
        image: localhost:5000/frontend
        ports:
        - containerPort: 8080
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: app
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 31000
