---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: /internal/metrics
    spec:
      containers:
      - name: backend2
        image: localhost:5000/backend2
        env:
        - name: JAVA_OPTS
          value: >-
            -Djava.rmi.server.hostname=127.0.0.1
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.rmi.port=8686
            -Dcom.sun.management.jmxremote.port=8686
            -Dcom.sun.management.jmxremote.local.only=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.authenticate=false
            -XX:StartFlightRecording=name=on_startup,filename=/root/flight_recording.jfr,dumponexit=true,delay=2m,maxsize=512m
            -Xms128m -Xmx128m
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
        - containerPort: 8082
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: backend2
spec:
  type: NodePort
  selector:
    app: backend2
  ports:
  - name: app
    protocol: TCP
    targetPort: 8082
    port: 8082
    nodePort: 31200
