---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: localhost:5000/backend2
        ports:
        - containerPort: 8082
        - containerPort: 8686

---
kind: Service
apiVersion: v1
metadata:
  name: backend2
spec:
  type: NodePort
  selector:
    app: backend2
  ports:
  - name: app
    protocol: TCP
    targetPort: 8082
    port: 8082
    nodePort: 31200
  - name: jmx
    protocol: TCP
    targetPort: 8686
    port: 8686
    nodePort: 31201
